
services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "444:444"
    depends_on:
      - database
    env_file:
      - ./backend/.env
    
    develop:
      watch:
        - action: sync+restart
          path: ./backend/
          target: /app
          
  database:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./backend/database.env


