
services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "444:444"
    depends_on:
      - database
      - ollama
    env_file:
      - ./backend/.env
    networks:
      - app-network
    volumes:
      - ./backend:/backend_app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

      


  database:
    image: pgvector/pgvector:pg17
    ports:
      - "5432:5432"
    env_file:
      - ./backend/database.env
    networks:
      - app-network

  test-database:
    image: pgvector/pgvector:pg17
    ports:
      - "5555:5432"
    env_file:
      - ./backend/database.env
    networks:
      - app-network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - app-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all


  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"  # Vite dev server
    depends_on:
      - backend
    volumes:
      - ./frontend:/app  # Sync code for live updates
      - /app/node_modules  # Prevent overwriting node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "dev", "--", "--host"]

volumes:
  ollama_data:

networks:
  app-network:
    driver: bridge


