FROM python:3.10-slim-bullseye

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV C_FORCE_ROOT true

WORKDIR /app
ADD . /app/

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN apt-get update
RUN apt install -y xmlsec1
RUN apt-get update && apt-get install -y curl

EXPOSE 444

RUN chmod +x docker-entrypoint.sh

ENTRYPOINT ["./docker-entrypoint.sh"]
