name: CI - Run Tests in Docker

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and start containers
        run: docker-compose up -d --build  # Runs in detached mode

      - name: Wait for services to be ready
        run: sleep 10  # Adjust if needed for startup time

      - name: Run backend tests
        run: docker-compose exec -T backend pytest tests  # Change "tests" to your test directory

      - name: Run frontend tests
        run: docker-compose exec -T frontend npm run test

      - name: Stop and clean up containers
        run: docker-compose down
