name: CI/CD-Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository # Checkout current version of repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: .env setup
        run: |
          echo "DATABASE_URI=${{ secrets.DATABASE_URI }}" > backend/.env
          echo "TEST_DATABASE_URI=${{ secrets.TEST_DATABASE_URI }}" >> backend/.env

      - name: database.env setup
        run: |
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" > backend/database.env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> backend/database.env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> backend/database.env
          echo "POSTGRES_HOST_AUTH_METHOD=${{ secrets.POSTGRES_HOST_AUTH_METHOD }}" >> backend/database.env

      - name: Set executable permissions for docker-entrypoint.sh
        run: chmod +x ./backend/docker-entrypoint.sh

      - name: Build containers
        run: docker-compose build -d

      - name: Start containers
        run: docker-compose up -d

      - name: Wait for services to be ready
        run: sleep 120

      - name: Start backend tests
        run: |
          docker-compose exec -T backend coverage run -m pytest -vv
          docker-compose exec -T backend coverage html -d /coverage/html
        continue-on-error: false # Continue running the pipeline even if backend tests fail

      - name: Run frontend tests
        run: docker-compose exec -T frontend npx vitest run --coverage
        env:
          CI: true
        continue-on-error: false # Continue running the pipeline even if backend tests fail

      # Wait for both tests to complete
      - name: Wait for tests to complete
        run: wait

      - name: Check backend logs
        run: docker-compose logs backend

      - name: Move backend coverage report to github repo
        run: |
          docker cp backend:/coverage/html ./documentation/static/backend/coveragefile/html/

      - name: Move frontend coverage report to github repo
        run: |
          docker cp frontend:/coverage/ ./documentation/static/frontend/coverage/

      - name: Check frontend logs
        run: docker-compose logs frontend

      - name: Stop and clean up containers
        run: docker-compose down # Finish tests
